inherit_from:
  - https://raw.githubusercontent.com/trailblazer/meta/master/rubocop.yml
  - .rubocop_todo.yml

Naming/MethodName:
  Exclude:
    - 'lib/trailblazer/operation/persist.rb'
    - 'lib/trailblazer/operation/contract.rb'

